version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - digistock_network
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  backend:
    image: araxel119/digistock-backend:latest
    ports:
      - "3000:3000"
    environment:
      # 🌍 Entorno general
      NODE_ENV: ${NODE_ENV:-production}

      # 🧩 Base de datos
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL: ${DB_SSL:-false}

      # 🔑 JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}

      # 🌐 n8n
      N8N_HOST: ${N8N_HOST:-n8n}
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL:-http://n8n:5678/webhook}
      N8N_PORT: ${N8N_PORT:-5678}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-America/Mexico_City}

      # ⚙️ CORS
      CORS_ORIGIN: ${CORS_ORIGIN:-http://frontend:80}

      # 📂 Subidas de archivos
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      UPLOAD_PATH: ${UPLOAD_PATH:-/app/uploads}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - n8n
    networks:
      - digistock_network
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: ${N8N_HOST:-n8n}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE:-true}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER:-admin}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD:-admin123}
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL:-http://n8n:5678/webhook}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-America/Mexico_City}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_flows:/home/node/.n8n/workflows
      - ./uploads:/app/uploads
    networks:
      - digistock_network
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  frontend:
    image: araxel119/digistock-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - digistock_network
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
  n8n_data:

networks:
  digistock_network:
    driver: overlay
